import { NextRequest, NextResponse } from 'next/server';
import { generateDocx } from '@/lib/export/docx-generator';

// PDF is generated by converting DOCX to a downloadable format
// For server-side PDF, we generate a structured HTML version
export async function POST(request: NextRequest) {
  try {
    const { report } = await request.json();

    if (!report || !report.sections) {
      return NextResponse.json(
        { error: 'Report data is required' },
        { status: 400 }
      );
    }

    // Generate HTML for PDF conversion client-side
    const html = generatePdfHtml(report);

    return NextResponse.json({ html });
  } catch (error) {
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to generate PDF' },
      { status: 500 }
    );
  }
}

interface Section {
  id: string;
  title: string;
  content: string;
}

interface Report {
  problemStatement: string;
  createdAt: string;
  sections: Section[];
}

const SECTION_COLORS: Record<string, string> = {
  'problem-breakdown': '#6366F1',
  stakeholders: '#8B5CF6',
  'solution-approach': '#EC4899',
  'action-plan': '#F59E0B',
};

function generatePdfHtml(report: Report): string {
  const sectionsHtml = report.sections
    .map((section: Section) => {
      const color = SECTION_COLORS[section.id] || '#6366F1';
      const content = markdownToHtml(section.content);
      return `
        <div style="margin-bottom: 32px; page-break-inside: avoid;">
          <div style="border-bottom: 2px solid ${color}; padding-bottom: 12px; margin-bottom: 20px;">
            <h2 style="color: ${color}; font-size: 24px; margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; letter-spacing: -0.5px; font-weight: 700;">${section.title}</h2>
          </div>
          <div style="font-size: 13.5px; line-height: 1.8; color: #334155; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding-bottom: 16px;">
            ${content}
          </div>
        </div>
      `;
    })
    .join('');

  return `
    <div id="pdf-content" style="max-width: 800px; margin: 0 auto; padding: 48px; background: white; font-family: 'Segoe UI', sans-serif;">
      <div style="text-align: center; margin-bottom: 48px; border-bottom: 2px solid #e2e8f0; padding-bottom: 32px;">
        <h1 style="font-size: 32px; color: #6366F1; margin-bottom: 12px;">Strategic Planning Report</h1>
        <p style="font-size: 16px; color: #64748b; font-style: italic; margin-bottom: 8px;">${report.problemStatement}</p>
        <p style="font-size: 12px; color: #94a3b8;">Generated on ${new Date(report.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>
      </div>
      ${sectionsHtml}
      <div style="text-align: center; margin-top: 48px; padding-top: 24px; border-top: 1px solid #e2e8f0;">
        <p style="font-size: 11px; color: #94a3b8; font-style: italic;">Generated by PlanForce AI — ForceEquals</p>
      </div>
    </div>
  `;
}

function markdownToHtml(md: string): string {
  return md
    .replace(/### (.+)/g, '<h4 style="color: #0f172a; font-size: 15px; margin: 20px 0 8px 0; font-weight: 700;">$1</h4>')
    .replace(/## (.+)/g, '<h3 style="color: #0f172a; font-size: 17px; margin: 24px 0 12px 0; font-weight: 700;">$1</h3>')
    .replace(/\*\*(.+?)\*\*/g, '<strong style="color: #0f172a;">$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`(.+?)`/g, '<code style="background: #f1f5f9; color: #0f172a; padding: 2px 6px; border-radius: 4px; font-size: 12px; border: 1px solid #e2e8f0;">$1</code>')
    .replace(/^- (.+)/gm, '<li style="margin-bottom: 8px;">$1</li>')
    .replace(/^(\d+)\. (.+)/gm, '<li style="margin-bottom: 8px;">$2</li>')
    .replace(/(<li.*<\/li>\n?)+/g, '<ul style="margin: 12px 0 20px 0; padding-left: 28px;">$&</ul>')
    .replace(/\n\n/g, '<div style="height: 16px;"></div>')
    .replace(/\n/g, '<br/>');
}
